### ISSUE TITLE
Normalization method does not work for samples where the medians for each row are 0.

### ISSUE THREAD

**Issue by CinchBlue** [lengning/OEFinder#2]
Currently, I'm trying to test out the Shiny application that's included with the repo. My data is this:

[count_table.zip](https://github.com/lengning/OEFinder/files/164066/count_table.zip)

This is an example dataset that we've included with our own workflow project that's hosted on GitHub. Using the default settings, the matrix ends up with a bunch of NAs. Why? Because of this expression chain within the function `MedianNorm` from `EBSeq`:

```
geomeans <- exp(rowMeans(log(Data)))
    out <- apply(Data, 2, function(cnts) median((cnts/geomeans)[geomeans > 
      0]))
```

Noticeably, if the `geomeans` end up being zero, things end up being NA.

**Comment by lengning** [comment]
Thanks for pointing this out!
The MedianNorm function in the latest version of EBSeq implemented an alternative way to normalize sc data when this issue happens. I'll incorporate the alternative normalization in OEFinder shortly.
Thanks
Ning
